### ISSUE TITLE
Get current seek time

### ISSUE THREAD

**Issue by amilajack** [Selz/plyr#307] opened 2016-07-09 21:46 UTC
How can I get the time that I have seeked to from an event listener?

```js
document.querySelector('.plyr').addEventListener('seeking', () => {
  console.log('seeking');
});
```

**Comment by SamPotts** [comment] 2016-07-09 23:36
Duplicate of #292 - I'll work on this later today if I get time.

**Closed by SamPotts** 2016-07-09 23:36 UTC
