### ISSUE TITLE
plyr not loaded with Require.js define dependency

### ISSUE THREAD

**Issue by franceer** [Selz/plyr#298] opened 2016-07-01 01:37 UTC
Hi,

I'm trying to load plyr via Require.js by using a module dependency like that:

`define(['jquery', 'plyr'], function (jquery, plyr) {`
`plyr.setup(); // plyr is null`
`});`

But the problem is that plyr is null.
I didn't used shim option since I saw that plyr is using define as expected by Require.js.

Do you have any idea why is this not working ? I also tried to do a require directly, but same result the module plyr is not loaded.

**Comment by franceer** [comment] 2016-07-01 02:10
For information I fixed the problem by changing the module declaration inside plyr.js file like so:

` } else if (typeof define === 'function' && define.amd) {`
        `// AMD`
        `define([], function () { return factory(root, document); });`
 `} else {`

As you can see I changed the null value by an empty array and I return the value from the factory so that I can use the plyr setup method in my own module.

I don't know if I'm doing right since I'm completely new on require.js, but for development purpose I will work like that for now. If you can enlight me on that issue when you get time, I'll appreciate :+1: 

Thank you for you help!

**Comment by SamPotts** [comment] 2016-07-05 05:10
Sorry, I'm going to need some help with this one. I've not used the module setup a great deal myself.

**Comment by franceer** [comment] 2016-07-05 09:11
Hi Sam,

I don't really know the changes required here but what I know is that I passed last couple of days to implement requirejs with node.js and the way the files or optimized and required is just a pain in... so I checked and it seems that webpack is the new robust method for that. So I'll change my implementation of plyr and will come back to you if I got better knowledge on AMD modules.

**Comment by mkaziz** [comment] 2016-08-01 19:45
@SamPotts I can confirm that @franceer's implementation helped me integrate this correctly with require.js.

**Comment by franceer** [comment] 2016-08-02 07:00
To add more info on this. I now use webpack with node.js to build my js files and the problem went away. For those using node.js, webpack seems so much better than require.js :)

**Comment by SamPotts** [comment] 2016-08-21 09:56
This should be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by ste93cry** [comment] 2016-08-26 11:02
The problem persist in 2.0.5, just tried it

**Comment by SamPotts** [comment] 2016-08-26 11:03
Feel free to jump in a with PR. Cheers

**Comment by ste93cry** [comment] 2016-08-26 11:11
I missed to specify that the fix that was merged above (#326) is not in 2.0.5. I don't know if this is wanted (because it was merged after that release or whatever) or not

**Comment by SamPotts** [comment] 2016-08-26 11:41
You're right! I think it's been lost in another merge. I'll re-add it now. Sorry about that.

**Comment by SamPotts** [comment] 2016-08-26 11:45
Just pushed a new version with the merge fixed up. Let me know if that's fixed it? 👍

**Comment by ste93cry** [comment] 2016-08-26 12:55
yay it works! Thank you

**Comment by shakeelmohamed** [comment] 2016-10-03 05:14
@SamPotts I think we can close this 😄

**Comment by SamPotts** [comment] 2016-10-03 05:15
Ta

**Closed by SamPotts** 2016-10-03 05:15 UTC
Labels: help wanted

**Comment by premhameed** [comment] 2017-01-23 10:36
Hi , 
It is not working for me

requirejs.config({
   
    baseUrl: 'js',
    paths: {
        'jquery':'jquery',       
        'bootstrap':'lib/bootstrap.min',
        'greensock':'lib/TweenMax.min',
        'waypoint':'lib/jquery.waypoints.min',
        'modernizr':'lib/modernizr',
        'aos':'lib/aos',
        'plyr':'lib/plyr',
        'home':'home',
        
    },
    shim: {
        
        'modernizr': [ "jquery" ],
        'bootstrap': ["jquery"],
        'aos': ["jquery"],
     
        
    },    
   
    
});


    
define(['jquery','modernizr','aos','greensock','waypoint','enhance','bootstrap','plyr'], function($,modernizer,AOS) {
  $(document).ready(function(){
plyr.setup();
});
});
