### ISSUE TITLE
Video doesn't play smoothly

### ISSUE THREAD

**Issue by Haroenv** [Selz/plyr#1] opened 2015-02-21 14:24 UTC
Safari, OSX Yosemite 10.10.2

The example on plyr.io doesn't play smoothly, when clicking on the fast-forward, it skips in time back and forward the complete rest of the video

**Comment by SamPotts** [comment] 2015-02-21 23:29
Hey there @Haroenv, Sorry to hear that. 

Plyr is really just a wrapper for the HTML5 native player so it could be an issue with the demo movie file, Safari playing up, your computer load, or your connection possibly. Are other videos having issues such as Vimeo? https://vimeo.com/108792063 (They also use a native <video> element). I get it sometimes if my CPU is getting smashed. 

Anyhow, I've pushed v1.0.9 which now displays the buffering progress, along with some other minor improvements. Maybe take a look and see if the movie hasn't loaded completely or something? 

![screen shot 2015-02-22 at 10 28 39 am](https://cloud.githubusercontent.com/assets/719092/6316532/a1d0739c-ba7d-11e4-8669-28f09061cd4a.png)

The darker progress is the amount of media that's buffered. You'll probably find on most machines it shoots up to 100% pretty quick.

**Comment by Haroenv** [comment] 2015-02-22 10:40
It still exhibits the same problem, but now the cause is clearer. The blue bar continues, even when not enough is buffered, this problem doesn't happen on vimeo, even skipping parts doesn't cause problems. 

I took a screen recording of it showing the problem [here](https://vid.me/xiDU)

**Comment by SamPotts** [comment] 2015-02-22 23:33
I'll do some more digging. Thanks for the vid. This might be an issue with the native <video> element that there's a work around for. I'll work something out and get back to you.

**Comment by SamPotts** [comment] 2015-03-22 12:17
Closing this one as I can't reproduce. If someone else is experiencing it, I'll take another look. Suspect it is network/machine related?

**Closed by SamPotts** 2015-03-22 12:17 UTC
Labels: bug

**Comment by Haroenv** [comment] 2015-03-22 18:19
Funny, I can't seem to reproduce it anymore either
