### ISSUE TITLE
Even though audio is mute displays tool tip as "Toggle Mute" as well as player is in full screen mode displays tool tip as "Toggle Full screen"

### ISSUE THREAD

**Issue by anupamabhise14** [Selz/plyr#229] opened 2016-05-19 13:00 UTC
**Steps to reproduce**
 - Hit the URL : https://plyr.io/#video
 - Player launches successfully.
 - Now let the video playback.
 - Now hover the volume icon and full screen icon
 - It displays tool tip for Volume icon as **Toggle Mute**  and for full screen icon displays tool tip as **Toggle Full screen**

***Actual Result***
 - Even though **volume is mute/unmute displays same tool tip as "Toggle Mute".**

Refer attachment : ![wrong_tooltip_for_volume](https://cloud.githubusercontent.com/assets/17408720/15394209/2de4d334-1def-11e6-9ab6-acbc89d3da14.png)

 - Even though **player is in normal or full screen mode displays same tool tip as "Toggle Full screen"**

Refer attachment :
 
![wrong_tooltip_for_fullscreen](https://cloud.githubusercontent.com/assets/17408720/15394280/9fdbaf08-1def-11e6-92f8-95424ecf20bf.png)

**Expected Result**
 - If **volume is Mute tool tip should displays as Toggle Unmute and viceversa.**
 - If **player is in Full screen mode then tool tip for full screen icon should display as "Toggle Normal Screen"**

**Comment by SamPotts** [comment] 2016-05-19 13:04
Sorry, not sure if they are bugs? They are toggle buttons and you are toggle the state of mute or fullscreen. If they were regular buttons, it would be 'enter/exit fullscreen' and 'mute/unmute'.

**Comment by alexdovzhanyn** [comment] 2016-05-21 03:22
I feel as though the intentions were misunderstood. I agree with Sam, this is not a bug. 'Toggle', by definition, means to turn on or off, depending on the state of the component.

**Comment by SamPotts** [comment] 2016-05-23 20:22
Closing this one for now

**Closed by SamPotts** 2016-05-23 20:22 UTC
