### ISSUE TITLE
Request: Youtube/Vimeo/Dailymotion support

### ISSUE THREAD

**Issue by AxelBriche** [Selz/plyr#73] opened 2015-03-31 13:29 UTC
Youtube/Vimeo/Dailymotion support :)

**Comment by ejb1123** [comment] 2015-04-02 22:18
similar request to #8

**Comment by SamPotts** [comment] 2015-04-05 03:54
Duplicate of #8 - I will get to it asap but need to build some sort of plugin framework first. :+1:

**Closed by SamPotts** 2015-04-05 03:54 UTC

**Comment by Jufik** [comment] 2017-01-23 18:23
Is there any support/example to support a Dailymotion video?

**Comment by ssuunaian** [comment] 2021-12-22 15:17
@sampotts still looking for it.
