### ISSUE TITLE
Feature request and issue with demo page

### ISSUE THREAD

**Issue by arjunmenon** [Selz/plyr#337] opened 2016-08-16 19:31 UTC
**Feature request** - Please add video quality options

**Issue** - Captions not visible in HTML5
            
         System - Elementary OS
         Browser - Firefox 48

**Comment by SamPotts** [comment] 2016-08-16 22:53
Firefox bug is a duplicate of #323 

Quality request is a duplicate of #218 

Please check before rasing issues 👍

**Closed by SamPotts** 2016-08-16 22:53 UTC
