### ISSUE TITLE
Problems with multiple YouTube embeds in the same page.

### ISSUE THREAD

**Issue by TheBITLINK** [Selz/plyr#306] opened 2016-07-09 08:44 UTC
If there are 2 or more from YouTube on the same page, neither of them will work properly: the seek bar will not move, and the play button will never go away.

![image](https://cloud.githubusercontent.com/assets/3434300/16706997/6f5fcdb0-458f-11e6-9001-05886c79cbdd.png)

For plyr, it's like the video never starts playing, but it is!

Also, as seen on the screenshot, the buffer bar still works properly, as well as pretty much everything else.

Tested on Chrome 54.0.2791.0 (Canary) and Firefox 49.0a2

**Comment by SamPotts** [comment] 2016-07-10 23:57
Sorry about this. Will take a look 👍

**Comment by linkthrow** [comment] 2016-08-04 09:13
+1

**Comment by SamPotts** [comment] 2016-08-04 09:15
Sorry about the delay - planning to spend a day this weekend on outstanding issues.

**Comment by linkthrow** [comment] 2016-08-04 09:17
@SamPotts No worries, happy to help if you need it. I was in the process of converting this into an Angular directive but ran into this problem! (https://github.com/linkthrow/angular-plyr)

**Comment by jbourassa** [comment] 2016-08-04 09:23
We are thinking of converting videos in our app to plyr and this struck as a very important issue, so I cloned the repo (`master`) and tried to reproduce the issue in order to fix it, but could not.

Can anyone share a snippet that reproduces it?

**Comment by linkthrow** [comment] 2016-08-04 10:06
I have managed to turn this plugin into an angular directive and got multiple youtube videos working (https://www.linkthrow.co/channel/10650/youtube-ifl-tv).

I don't know if its the isolated scopes of the directives, but I hope this helps you in debugging!

Over the weekend I will release a production ready wrapper!

**Comment by jbourassa** [comment] 2016-08-04 10:15
> I have managed to turn this plugin into an angular directive and got multiple youtube videos working (https://www.linkthrow.co/channel/10650/youtube-ifl-tv).

Yeah this is pretty much exactly what I'm saying — we can't reproduce the issue. Maybe it has been fixed?

**Comment by linkthrow** [comment] 2016-08-04 12:26
Not sure as I have not deployed as a standalone app, Angular has isolated scopes so it may not occur for me coincidently.

**Comment by jbourassa** [comment] 2016-08-04 13:48
@linkthrow As far as I know, there's no link between Angular's isolated scope and how plyr works — isolated scopes are internal to angular and does not affect plyr.

**Comment by TheBITLINK** [comment] 2016-08-05 02:23
Well, i just noticed it only happens under very specific conditions. I don't know exactly which, but here are some samples:
https://thebit.link/plyr-test/ [broken]
https://codepen.io/TheBITLINK/pen/vKVkyb/left?editors=1000 [not broken]

**Comment by jbourassa** [comment] 2016-08-05 08:50
@TheBITLINK You are not loading the same version of plyr in both example. One codepen (working ) example has `1.8.12` (lastest), whereas your Ghost website has `1.8.7`. I downloaded the html page, updated plyr and everything was fine.

**Comment by TheBITLINK** [comment] 2016-08-05 13:35
I tried both versions on the codepen, and also on my blog (i forgot to restart Ghost and it cached the old version), but it's updated now, and still the same.

**Comment by jbourassa** [comment] 2016-08-05 13:39
That is super strange because it now works on my end: 
![screen shot 2016-08-05 at 3 38 45 pm](https://cloud.githubusercontent.com/assets/224311/17438377/cb8c75ea-5b22-11e6-8c98-e46b2f338ae2.png)

Does it work for you in Chrome?

**Comment by TheBITLINK** [comment] 2016-08-05 16:38
Weird, doesn't work in Chrome either
![image](https://cloud.githubusercontent.com/assets/3434300/17443599/74f50ed6-5b09-11e6-9665-eca2498982a8.png)

**Comment by SamPotts** [comment] 2016-08-21 09:56
This *may* be fixed in v1.9.0 - could you give it a go? Bear in mind there were also several breaking changes so check the [changelog](https://github.com/Selz/plyr/blob/master/changelog.md)

**Comment by Veyfeyken** [comment] 2016-10-13 09:42
Any chance this gets fixed? I can no longer recommend Plyr as a good alternative in our accessibility audits until this gets solved. Sorry I can't help out personally. Limited experience with JS.

**Comment by linkthrow** [comment] 2016-10-13 09:44
@Veyfeyken what is your stack that you are using it with?

**Comment by SamPotts** [comment] 2016-10-13 09:50
As I said before, I couldn't replicate (and still can't). If you could give me some more info, like a code sample. That would help. 

Here's two working with v2.0.7. I can't see any issues with it:
http://codepen.io/sampotts/pen/mAKjAp

**Comment by Veyfeyken** [comment] 2016-10-13 10:55
Example: [https://www.abconcerts.be/nl/agenda/evenementen/tout-va-bien/20004/](https://www.abconcerts.be/nl/agenda/evenementen/tout-va-bien/20004/)

They're using:
`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="plyr" src="//cdn.plyr.io/2.0.7/plyr.js?v=r59">`

**Comment by SamPotts** [comment] 2016-10-13 12:02
I've been trying to debug that page and I'm not sure what's causing it to break. It's obvious the player works in isolation so it's gotta be something to do with the implementation. I notice there's jplayer on the page too which could be an issue. The YouTube API uses postMessage from the iframe to parent so it's also possible that there's some sort of postMessage handler screwing it up. I'd look at that first.

**Comment by Veyfeyken** [comment] 2016-10-17 07:02
Thanks for the feedback.

**Closed** 2016-10-23 02:49 UTC
Labels: bug
