### ISSUE TITLE
youtube captions

### ISSUE THREAD

**Issue by WAUnique** [Selz/plyr#398] opened 2016-10-19 16:19 UTC
How can I add external captions for youtube video?
Thank you

**Comment by scshepard** [comment] 2016-10-19 17:48
Hi,

If you mean "subtitles" within the video, you must be the owner of the video. If you are, select the video, then access the commands. Sorry, my channel is "missing" so I can't walk you through the steps.

Steve

________________________________

**Comment by WAUnique** [comment] 2016-10-20 02:50
I mean: I have an youtube video (not owner, url only), can I add external subtitles (owner) (captions.vtt)?

**Comment by SamPotts** [comment] 2016-10-23 01:33
Duplicate of #383 - please check before raising existing issues 👍

**Closed by SamPotts** 2016-10-23 01:33 UTC

**Comment by friday** [comment] 2018-07-07 18:58
#383 is about annotations, so this wasn't really a duplicate. I just created #1090 so if you see this, go there.
